import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";
import pluginReact from "eslint-plugin-react";
import json from "@eslint/json";
import markdown from "@eslint/markdown";
import css from "@eslint/css";
import { defineConfig } from "eslint/config";
import jsdoc from "eslint-plugin-jsdoc";
import pluginImport from "eslint-plugin-import";

export default defineConfig([
  {
    name: "global/ignores",
    ignores: [
      ".next/**/*",
      "dist/**/*",
      "node_modules/**/*",
      "out/**/*",
      "public/**/*",
    ],
  },
  {
    name: "eslint",
    files: ["**/*.{js,mjs,cjs,ts,jsx,tsx}"],
    plugins: { js },
    extends: ["js/recommended"],
    rules: {
      "arrow-body-style": ["error", "always"],
      curly: ["error", "all"],
      "no-implicit-coercion": "error",
      "prefer-template": "error",
      "require-await": "error",
    },
  },
  {
    files: ["**/*.{js,mjs,cjs,ts,jsx,tsx}"],
    languageOptions: { globals: globals.browser },
  },
  tseslint.configs.recommended,
  {
    name: "jsdoc",
    files: ["**/*.{js,mjs,cjs,ts,jsx,tsx}"],
    extends: [jsdoc.configs["flat/recommended-typescript-error"]],
    rules: {
      "jsdoc/check-tag-names": [
        "error",
        {
          definedTags: [
            "abstract",
            "alpha",
            "augments",
            "author",
            "beta",
            "callback",
            "category",
            "categoryDescription",
            "class",
            "default",
            "defaultValue",
            "deprecated",
            "disableGroups",
            "document",
            "enum",
            "event",
            "eventProperty",
            "example",
            "expand",
            "expandType",
            "experimental",
            "extends",
            "function",
            "group",
            "groupDescription",
            "hidden",
            "hideCategories",
            "hideconstructor",
            "hideGroups",
            "ignore",
            "import",
            "include",
            "includeCode",
            "inheritDoc",
            "inline",
            "inlineType",
            "interface",
            "internal",
            "jsx",
            "label",
            "license",
            "link",
            "linkcode",
            "linkplain",
            "mergeModuleWith",
            "module",
            "namespace",
            "overload",
            "override",
            "packageDocumentation",
            "param",
            "preventExpand",
            "preventInline",
            "primaryExport",
            "private",
            "privateRemarks",
            "prop",
            "property",
            "protected",
            "public",
            "readonly",
            "remarks",
            "return",
            "returns",
            "satisfies",
            "sealed",
            "see",
            "showCategories",
            "showGroups",
            "since",
            "summary",
            "template",
            "throws",
            "type",
            "typedef",
            "typeParam",
            "useDeclaredType",
            "virtual",
            "yields",
          ],
        },
      ],
      "jsdoc/require-description": ["off"],
      "jsdoc/require-jsdoc": ["off"],
      "jsdoc/require-param": ["off"],
      "jsdoc/require-returns": ["off"],
      "jsdoc/sort-tags": [
        "error",
        {
          reportIntraTagGroupSpacing: false,
        },
      ],
      "jsdoc/tag-lines": [
        "error",
        "always",
        {
          applyToEndTag: false,
          startLines: 1,
        },
      ],
    },
  },
  {
    name: "import",
    files: ["**/*.{js,mjs,cjs,ts,jsx,tsx}"],
    plugins: {
      import: pluginImport,
    },
    rules: {
      "import/consistent-type-specifier-style": ["error", "prefer-top-level"],
      "import/no-duplicates": "error",
    },
  },
  pluginReact.configs.flat.recommended,
  {
    files: ["**/*.json"],
    plugins: { json },
    language: "json/json",
    extends: ["json/recommended"],
  },
  {
    files: ["**/*.jsonc"],
    plugins: { json },
    language: "json/jsonc",
    extends: ["json/recommended"],
  },
  {
    files: ["**/*.json5"],
    plugins: { json },
    language: "json/json5",
    extends: ["json/recommended"],
  },
  {
    files: ["**/*.md"],
    plugins: { markdown },
    language: "markdown/gfm",
    extends: ["markdown/recommended"],
  },
  {
    files: ["**/*.css"],
    plugins: { css },
    language: "css/css",
    extends: ["css/recommended"],
  },
]);
